spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie_review
    username: dayoung
    password: 1234

mybatis:
  #  mapper ??? ??? ?????. ?? ??? mapper ???? ??? ?? xml ??? ?????.
  mapper-locations: mapper/**/*.xml
  configuration:
    # db ????? ???? ??? ?????? ???? ?????.
    map-underscore-to-camel-case: true
  # @Alias? ???? ??? ?????. ?? ??? ????? ??? ?????.
  type-aliases-package: com.moondy.moviereview